# Generated by Django 4.1.2 on 2022-10-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.CharField(max_length=500, null=True, verbose_name='Подробная информация'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Если данный пункт отмечен - объявление размещено', verbose_name='Объявление размещено?'),
        ),
    ]
