# Generated by Django 4.1.2 on 2022-10-16 13:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0003_selections'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Selections',
            new_name='Selection',
        ),
    ]
